version: "3.5"
   
services:
  web-server:
    image: 'nginx'
    ports:
      - 80:80
      - 443:443
    links:
      - backend:backend
    depends_on:
       - backend
    volumes:
      - ./front:/var/www/front
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/vending:/backend
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
